#!/bin/sh
#set -x

TOOL_NAME="Microsoft Office 2016 Disable Store Tool"
TOOL_VERSION="1.1"

## Copyright (c) 2017 Microsoft Corp. All rights reserved.
## Scripts are not supported under any Microsoft standard support program or service. The scripts are provided AS IS without warranty of any kind.
## Microsoft disclaims all implied warranties including, without limitation, any implied warranties of merchantability or of fitness for a 
## particular purpose. The entire risk arising out of the use or performance of the scripts and documentation remains with you. In no event shall
## Microsoft, its authors, or anyone else involved in the creation, production, or delivery of the scripts be liable for any damages whatsoever 
## (including, without limitation, damages for loss of business profits, business interruption, loss of business information, or other pecuniary 
## loss) arising out of the use of or inability to use the sample scripts or documentation, even if Microsoft has been advised of the possibility
## of such damages.
## Feedback: pbowden@microsoft.com

# Constants
WORD2016PATH="/Applications/Microsoft Word.app"
EXCEL2016PATH="/Applications/Microsoft Excel.app"
POWERPOINT2016PATH="/Applications/Microsoft PowerPoint.app"
OUTLOOK2016PATH="/Applications/Microsoft Outlook.app"
ONENOTE2016PATH="/Applications/Microsoft OneNote.app"
SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )

function ShowUsage {
# Shows tool usage and parameters
	echo $TOOL_NAME - $TOOL_VERSION
	echo "Purpose: Removes the Store and Add-in icons from the ribbon in Office 2016 for Mac apps"
	echo "Usage: DisableStore [--True] [--False]"
	echo "Example: DisableStore --True"
	echo
	exit 0
}

# Check that all ribbon-integrated applications (Word/Excel/PowerPoint) are not running
function CheckRunning {
	OPENAPPS=0
	WORDRUNSTATE=$(CheckLaunchState "$WORD2016PATH")
	if [ "$WORDRUNSTATE" == "1" ]; then
		OPENAPPS=$(($OPENAPPS + 1))
	fi
	EXCELRUNSTATE=$(CheckLaunchState "$EXCEL2016PATH")
	if [ "$EXCELRUNSTATE" == "1" ]; then
		OPENAPPS=$(($OPENAPPS + 1))
	fi
	POWERPOINTRUNSTATE=$(CheckLaunchState "$POWERPOINT2016PATH")
	if [ "$POWERPOINTRUNSTATE" == "1" ]; then
		OPENAPPS=$(($OPENAPPS + 1))
	fi
	if [ "$OPENAPPS" != "0" ]; then
		echo "1"
	else
		echo "0"
	fi
}

# Checks to see if a process is running
function CheckLaunchState {
	APPPATH="$1"
	local RUNNING_RESULT=$(ps ax | grep -v grep | grep "$APPPATH")
	if [ "${#RUNNING_RESULT}" -gt 0 ]; then
		echo "1"
	else
		echo "0"
	fi
}

function CreateRibbonCustomization {
# Creates the .officeUI file that holds the ribbon customization
	APPFILE="$1"
	APPNAME="$2"
	if [ ! -d $HOME/Library/Containers/com.microsoft.$APPNAME/Data/Library/Preferences ]; then
		mkdir -p "$HOME/Library/Containers/com.microsoft.$APPNAME/Data/Library/Preferences"
	fi
	touch "$HOME/Library/Containers/com.microsoft.$APPNAME/Data/Library/Preferences/$APPFILE.officeUI"
	echo "<mso:customUI xmlns:mso=\"http://schemas.microsoft.com/office/2009/07/customui\"><mso:ribbon><mso:qat/><mso:tabs><mso:tab idQ=\"mso:TabInsert\"><mso:group idQ=\"mso:GroupOfficeExtension\" visible=\"false\"/></mso:tab></mso:tabs></mso:ribbon></mso:customUI>
" >> "$HOME/Library/Containers/com.microsoft.$APPNAME/Data/Library/Preferences/$APPFILE.officeUI"
}

function RemoveRibbonCustomization {
# Removes the .officeUI file that holds the ribbon customization
	APPFILE="$1"
	APPNAME="$2"
	rm -f "$HOME/Library/Containers/com.microsoft.$APPNAME/Data/Library/Preferences/$APPFILE.officeUI"
}

# Evaluate command-line arguments
if [[ $# = 0 ]]; then
	ShowUsage
else
	for KEY in "$@"
	do
	case $KEY in
    	--Help|-h|--help)
    	ShowUsage
    	shift # past argument
    	;;
    	--True|-t|--true)
    	ENABLE=true
    	shift # past argument
		;;
		--False|-f|--false)
		DISABLE=true
		shift # past argument
		;;
		*)
    	ShowUsage
    	;;
    esac
	shift # past argument or value
	done
fi

## Main
if [ $ENABLE ]; then
	APPSRUNNING=$(CheckRunning)
	if [ "$APPSRUNNING" == "1" ]; then
		echo "ERROR: Office 2016 apps are open. Quit Word, Excel and PowerPoint and re-run the tool."
		echo
		exit 1
	fi
	CreateRibbonCustomization "Word" "Word"
	CreateRibbonCustomization "Excel" "Excel"
	CreateRibbonCustomization "Powerpoint" "PowerPoint"
	echo "Store and Add-in icons have been removed."
elif [ $DISABLE ]; then
	APPSRUNNING=$(CheckRunning)
	if [ "$APPSRUNNING" == "1" ]; then
		echo "ERROR: Office 2016 apps are open. Quit Word, Excel and PowerPoint and re-run the tool."
		echo
		exit 1
	fi
	RemoveRibbonCustomization "Word" "Word"
	RemoveRibbonCustomization "Excel" "Excel"
	RemoveRibbonCustomization "Powerpoint" "PowerPoint"
	echo "All ribbon customizations have been reverted."
fi 

echo
exit 0